#!/bin/bash

#Volume control script and notify the volume
#I'm using dunst for the notification and pamixer for the audio control

case "$1" in 
	0) pamixer -d 1 ;;
	1) pamixer -i 1 ;;
	mute) pamixer -t ;;
esac

	
#get the current volume

current_volume=$(pamixer --get-volume)

#use dunstify to notify the volume level
# -r replaces the notification with ID so the screen isn't flooded when constantly increasing volume
# -t sets the time to given in ms
#dunstify -r 1000 -t 1500 $current_volume

if [ "$(pamixer --get-mute)" != "true" ]; then
	dunstify \
	-I ~/.local/share/icons/dunst/bell.png \
	-r 1000 \
	-t 1500 \
	-h int:value:$current_volume $current_volume
else
	dunstify \
		-I ~/.local/share/icons/dunst/mute-color.png \
		-r 1000 \
		-t 1500 \
		-h int:value:$current_volume $current_volume \
		"Muted"
fi
